# Beginner difficulty
EASY_GRID_SIZE = (9, 9)
EASY_NUM_MINES = 10

# Intermediate difficulty
MEDIUM_GRID_SIZE = (16, 16)
MEDIUM_NUM_MINES = 40

# Expert difficulty
HARD_GRID_SIZE = (16, 30)
HARD_NUM_MINES = 99

CONFIG_DIFFICULTY = [
    [EASY_GRID_SIZE, EASY_NUM_MINES],
    [MEDIUM_GRID_SIZE, MEDIUM_NUM_MINES],
    [HARD_GRID_SIZE, HARD_NUM_MINES]
]